version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  app:
    build: .
    command: /api
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: